# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: plotspotter.org
email: david@plotspotter.org
description: > # this means to ignore newlines until "baseurl:"
  In this blog I will talk about interesting stats and data visulisations in R.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: davidhuels
github_username:  davidhuels
google_analytics: UA-98095323-1
logo: /assets/plotspotter_logo_original.png

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock

# Name of repository, for use with Staticman
repository: "davidhuels/davidhuels.github.io"

# Staticman comments (see staticman.yml for configuration).
staticman:
  branch: "master"



